language: go

go:
  - 1.9.x

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
install:
  - dep ensure
script:
  - go test -cover ./...
  - test -z "$(go fmt | tee /dev/stderr)"
  - test -z "$(golint | tee /dev/stderr)"
