language: go

go:
  - 1.9.x

before_install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/golang/lint/golint
install:
  - dep ensure
script:
  - go test ./...
  - test -z $(go fmt)
  - test -z $(golint)
