apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: git-branch-mirroring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: git-branch-mirroring
    spec:
      containers:
        - name: git-branch-mirroring
          image: marstr/mirrorcat
          ports:
          - containerPort: 8080
            name: mirrorcat
---
apiVersion: v1
kind: Service
metadata:
  name: git-branch-mirroring
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: git-branch-mirroring
